Vagrant.configure("2") do |config|
    config.vm.define "mdailletS" do |mdailletS|
        mdailletS.vm.box = "centos/8"
        mdailletS.vm.hostname = "mdailletS"
        mdailletS.vm.network "private_network", ip: "192.168.56.110"
        mdailletS.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end
        mdailletS.vm.provision "shell", inline: <<-SHELL
            curl -sfl https://get.k3s.io | sh -
        SHELL
    end

    config.vm.define "mdailletSW" do |mdailletSW|
        mdailletSW.vm.box = "centos/8"
        mdailletSW.vm.hostname = "mdailletSW"
        mdailletSW.vm.network "private_network", ip: "192.168.56.111"
        mdailletSW.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
        end
        mdailletSW.vm.provision "shell", inline: <<-SHELL
            curl -sfl https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=token sh-
        SHELL
    end

end